### ISSUE TITLE
stream_to的patch

### ISSUE THREAD

**Issue by darcyg** [w-mj/Pysh#1]
[001-stream_to-stderr.zip](https://github.com/w-mj/Pysh/files/8776133/001-stream_to-stderr.zip)
因为要用pv，结果发现pv拷贝的时候信息输出到stderr了。原代码没stderr，就加了一个
所以做了补丁。另外在Popen的时候，我改了代码增加了  shell=True, universal_newlines=True 参数
cmd里面如果用管道和参数一类，现有的Exec方法总报错
pv有点特殊，必须加-W -f命令才能增城截取。下面是参考代码

> setCatPVCB(cb)
    f = FuncFilter(filterCatPV)
    print(os.path.getsize(srcFile))
    srcSize = math.ceil(os.path.getsize(srcFile)/(1024*1024)/1.020)
    mkdirCmd="mkdir -p $(dirname {})".format(dstFile)
    cpCmd="cat {} | pv -W -f -s {}M -b -t -e -r -a -p > {} ".format(srcFile,srcSize,dstFile)
    print(cpCmd)
    Exec(mkdirCmd).stdout()
    #print(Exec(cpCmd).stream_to(f).stdout())
    Exec(cpCmd).stream_to(f).stderr()

**Comment by w-mj** [comment]
感谢建议，已合并您的补丁。
